// https://www.kreativekorp.com/ucsur/charts/sitelen.html

export const START_OF_CARTOUCHE = "\u{F1990}";
export const END_OF_CARTOUCHE = "\u{F1991}";
export const COMBINING_CARTOUCHE_EXTENSION = "\u{F1992}";
export const START_OF_LONG_PI = "\u{F1993}";
export const COMBINING_LONG_PI_EXTENSION = "\u{F1994}";
export const STACKING_JOINER = "\u{F1995}";
export const SCALING_JOINER = "\u{F1996}";
export const START_OF_LONG_GLYPH = "\u{F1997}";
export const END_OF_LONG_GLYPH = "\u{F1998}";
export const COMBINING_LONG_GLYPH_EXTENSION = "\u{F1999}";
export const START_OF_REVERSE_LONG_GLYPH = "\u{F199A}";
export const END_OF_REVERSE_LONG_GLYPH = "\u{F199B}";
export const UCSUR_MIDDLE_DOT = "\u{F199C}";
export const UCSUR_COLON = "\u{F199D}";
export const COMBINING_TALLY_MARK = "\u{F199E}";

export const SPECIAL_UCSUR_DESCRIPTIONS = {
  [START_OF_CARTOUCHE]: "start of cartouche",
  [END_OF_CARTOUCHE]: "end of cartouche",
  [COMBINING_CARTOUCHE_EXTENSION]: "combining cartouche extension",
  [START_OF_LONG_PI]: "start of long pi",
  [COMBINING_LONG_PI_EXTENSION]: "combining long pi extension",
  [STACKING_JOINER]: "stacking joiner",
  [SCALING_JOINER]: "scaling joiner",
  [START_OF_LONG_GLYPH]: "start of long glyph",
  [END_OF_LONG_GLYPH]: "end of long glyph",
  [COMBINING_LONG_GLYPH_EXTENSION]: "combining long glyph extension",
  [START_OF_REVERSE_LONG_GLYPH]: "start of reverse long glyph",
  [END_OF_REVERSE_LONG_GLYPH]: "end of reverse long glyph",
  [UCSUR_MIDDLE_DOT]: "middle dot",
  [UCSUR_COLON]: "colon",
  [COMBINING_TALLY_MARK]: "combining tally mark",
};

export type SpecialUcsur = keyof typeof SPECIAL_UCSUR_DESCRIPTIONS;

export const PU_WORDS = [
  "a",
  "akesi",
  "ala",
  "alasa",
  "ale",
  "anpa",
  "ante",
  "anu",
  "awen",
  "e",
  "en",
  "esun",
  "ijo",
  "ike",
  "ilo",
  "insa",
  "jaki",
  "jan",
  "jelo",
  "jo",
  "kala",
  "kalama",
  "kama",
  "kasi",
  "ken",
  "kepeken",
  "kili",
  "kiwen",
  "ko",
  "kon",
  "kule",
  "kulupu",
  "kute",
  "la",
  "lape",
  "laso",
  "lawa",
  "len",
  "lete",
  "li",
  "lili",
  "linja",
  "lipu",
  "loje",
  "lon",
  "luka",
  "lukin",
  "lupa",
  "ma",
  "mama",
  "mani",
  "meli",
  "mi",
  "mije",
  "moku",
  "moli",
  "monsi",
  "mu",
  "mun",
  "musi",
  "mute",
  "nanpa",
  "nasa",
  "nasin",
  "nena",
  "ni",
  "nimi",
  "noka",
  "o",
  "olin",
  "ona",
  "open",
  "pakala",
  "pali",
  "palisa",
  "pan",
  "pana",
  "pi",
  "pilin",
  "pimeja",
  "pini",
  "pipi",
  "poka",
  "poki",
  "pona",
  "pu",
  "sama",
  "seli",
  "selo",
  "seme",
  "sewi",
  "sijelo",
  "sike",
  "sin",
  "sina",
  "sinpin",
  "sitelen",
  "sona",
  "soweli",
  "suli",
  "suno",
  "supa",
  "suwi",
  "tan",
  "taso",
  "tawa",
  "telo",
  "tenpo",
  "toki",
  "tomo",
  "tu",
  "unpa",
  "uta",
  "utala",
  "walo",
  "wan",
  "waso",
  "wawa",
  "weka",
  "wile",
];
export const KU_SULI_WORDS = [
  "namako",
  "kin",
  "oko",
  "kipisi",
  "leko",
  "monsuta",
  "tonsi",
  "jasima",
  "kijetesantakalu",
  "soko",
  "meso",
  "epiku",
  "kokosila",
  "lanpan",
  "n",
  "misikeke",
  "ku",
];
export const VARIANTS = [
  "ni",
  "ni",
  "ni",
  "sewi",
];
export const OTHER_WORDS = [
  "pake",
  "apeja",
  "majuna",
  "powe",
  "linluwi",
  "kiki",
  "su",
  "isipin",
  "kamalawala",
  "kapesi",
  "melome",
  "mijomi",
  "misa",
  "nimisin",
  "nja",
  "oke",
  "omekapo",
  "puwa",
  "san",
  "taki",
  "te",
  "to",
  "unu",
  "usawi",
  "wa",
  "wuwojiti",
  "yupekosi",
];
export const UCSUR_TO_LATIN = new Map(
  [
    { start: 0xF1900, words: [...PU_WORDS, ...KU_SULI_WORDS, ...VARIANTS] },
    { start: 0xF19A0, words: OTHER_WORDS },
  ]
    .flatMap(({ start, words }) =>
      words.map((latin, i) => [String.fromCodePoint(start + i), latin] as const)
    ),
);
export const UCSUR_CHARACTER_REGEX =
  /[\u{F1900}-\u{F1988}\u{F19A0}-\u{F19A3}]/u;
