export const START_OF_CARTOUCHE = "\u{F1990}";
export const END_OF_CARTOUCHE = "\u{F1991}";
export const COMBINING_CARTOUCHE_EXTENSION = "\u{F1992}";
export const START_OF_LONG_PI = "\u{F1993}";
export const COMBINING_LONG_PI_EXTENSION = "\u{F1994}";
export const STACKING_JOINER = "\u{F1995}";
export const SCALING_JOINER = "\u{F1996}";
export const START_OF_LONG_GLYPH = "\u{F1997}";
export const END_OF_LONG_GLYPH = "\u{F1998}";
export const COMBINING_LONG_GLYPH_EXTENSION = "\u{F1999}";
export const START_OF_REVERSE_LONG_GLYPH = "\u{F199A}";
export const END_OF_REVERSE_LONG_GLYPH = "\u{F199B}";
export const MIDDLE_DOT = "\u{F199C}";
export const COLON = "\u{F199D}";

export const UCSUR_TO_LATIN: { [ucsur: string]: string } = {
  "󱤀": "a",
  "󱤁": "akesi",
  "󱤂": "ala",
  "󱤃": "alasa",
  "󱤄": "ale",
  "󱤅": "anpa",
  "󱤆": "ante",
  "󱤇": "anu",
  "󱤈": "awen",
  "󱤉": "e",
  "󱤊": "en",
  "󱤋": "esun",
  "󱤌": "ijo",
  "󱤍": "ike",
  "󱤎": "ilo",
  "󱤏": "insa",
  "󱤐": "jaki",
  "󱤑": "jan",
  "󱤒": "jelo",
  "󱤓": "jo",
  "󱤔": "kala",
  "󱤕": "kalama",
  "󱤖": "kama",
  "󱤗": "kasi",
  "󱤘": "ken",
  "󱤙": "kepeken",
  "󱤚": "kili",
  "󱤛": "kiwen",
  "󱤜": "ko",
  "󱤝": "kon",
  "󱤞": "kule",
  "󱤟": "kulupu",
  "󱤠": "kute",
  "󱤡": "la",
  "󱤢": "lape",
  "󱤣": "laso",
  "󱤤": "lawa",
  "󱤥": "len",
  "󱤦": "lete",
  "󱤧": "li",
  "󱤨": "lili",
  "󱤩": "linja",
  "󱤪": "lipu",
  "󱤫": "loje",
  "󱤬": "lon",
  "󱤭": "luka",
  "󱤮": "lukin",
  "󱤯": "lupa",
  "󱤰": "ma",
  "󱤱": "mama",
  "󱤲": "mani",
  "󱤳": "meli",
  "󱤴": "mi",
  "󱤵": "mije",
  "󱤶": "moku",
  "󱤷": "moli",
  "󱤸": "monsi",
  "󱤹": "mu",
  "󱤺": "mun",
  "󱤻": "musi",
  "󱤼": "mute",
  "󱤽": "nanpa",
  "󱤾": "nasa",
  "󱤿": "nasin",
  "󱥀": "lupa",
  "󱥁": "ni",
  "󱥂": "nimi",
  "󱥃": "noka",
  "󱥄": "o",
  "󱥅": "olin",
  "󱥆": "ona",
  "󱥇": "open",
  "󱥈": "pakala",
  "󱥉": "pali",
  "󱥊": "palisa",
  "󱥋": "pan",
  "󱥌": "pana",
  "󱥍": "pi",
  "󱥎": "pilin",
  "󱥏": "pimeja",
  "󱥐": "pini",
  "󱥑": "pipi",
  "󱥒": "poka",
  "󱥓": "poki",
  "󱥔": "pona",
  "󱥕": "pu",
  "󱥖": "sama",
  "󱥗": "seli",
  "󱥘": "selo",
  "󱥙": "seme",
  "󱥚": "sewi",
  "󱥛": "sijelo",
  "󱥜": "sike",
  "󱥝": "sin",
  "󱥞": "sina",
  "󱥟": "sinpin",
  "󱥠": "sitelen",
  "󱥡": "sona",
  "󱥢": "soweli",
  "󱥣": "suli",
  "󱥤": "suno",
  "󱥥": "supa",
  "󱥦": "suwi",
  "󱥧": "tan",
  "󱥨": "taso",
  "󱥩": "tawa",
  "󱥪": "telo",
  "󱥫": "tenpo",
  "󱥬": "toki",
  "󱥭": "tomo",
  "󱥮": "tu",
  "󱥯": "unpa",
  "󱥰": "uta",
  "󱥱": "utala",
  "󱥲": "walo",
  "󱥳": "wan",
  "󱥴": "waso",
  "󱥵": "wawa",
  "󱥶": "weka",
  "󱥷": "wile",
  "󱥸": "namako",
  "󱥹": "kin",
  "󱥺": "oko",
  "󱥻": "kipisi",
  "󱥼": "leko",
  "󱥽": "monsuta",
  "󱥾": "tonsi",
  "󱥿": "jasima",
  "󱦀": "kijetesantakalu",
  "󱦁": "soko",
  "󱦂": "meso",
  "󱦃": "epiku",
  "󱦄": "kokosila",
  "󱦅": "lanpan",
  "󱦆": "n",
  "󱦇": "misikeke",
  "󱦈": "ku",
  "󱦠": "pake",
  "󱦡": "apeja",
  "󱦢": "majuna",
  "󱦣": "powe",
};
