name: Deno

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build Dictionary
        run: deno task build-dictionary
      - name: Check formatting
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test
